[package]
name = "db"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
thiserror = { workspace = true }
tracing = { workspace = true}
